---
title: Detección de SNPs outliers entre dos tipos de paisajes que habita la lagartija *Sceloporus grammicus*
author: "Óscar Romero Báez"
date: '2022-05-25'
output: html_document
---

## Planteamiento del problema

Los paisajes perturbados a gran escala, debido a las actividades humanas, han generado grandes desafíos a la vida silvestre. Provocando que se enfrenten en mayor medida a entornos extremos y novedosos, que pueden ponerlos en riesgo al afectar su sobrevivencia (Campebell-Staton *et al*., 2020). Sin embargo, se ha visto que algunas especies que han entrado en contacto a estos entornos, muestran adaptaciones a variables que imponen estos paisajes (Salmon *et al*., 2021).

Algunas adaptaciones están relacionadas con la tolerancia a niveles altos de ruido, luz artificial en las noches, temperaturas altas y modificaciones en la dieta (Winchell *et al*., 2018). También hay adaptaciones asociadas al cambio conductual, morfológico y locomotor (Audet *et al*, 2016; Revel *et al*., 2016). Tales evidencias han permitido identificar la existencia de divergencia adaptativa entre poblaciones naturales y perturbadas. Asimismo, de que tiene una base genética y que ocurre en escalas de tiempo cortas, principalmente en respuesta a las actividades humanas (Hendry *et al*., 2008; Reid *et al*., 2016; Campebell-Staton *et al*., 2020).

Entender los mecanismos que generan la divergencia adaptativa podría proporcionar información relevante sobre la magnitud del cambio evolutivo inducido por los paisajes perturbados en las especies (Salmon *et al*., 2021). Además, de indicar el potencial que tienen para colonizar con éxito este tipo de paisajes y si este patrón se repite en diferentes sitios (Campebell-Staton *et al*., 2020).

## Preguntas

Una especie que puede habitar en paisajes naturales y perturbados, es la lagartija *Sceloporus grammicus*. En la cual se han observado modificaciones en su conducta, patrones reproductivos, de coloración y morfológicos cuando habitan sitios perturbados (Argaez-Márquez, 2015). Por tales razones, es un buen modelo para investigar si existen diferentes SNPs outliers, candidatos bajo selección, que puedan llevar a una divergencia adaptativa en *S. grammicus*, esto al comparar paisajes naturales y perturbados. Además, de saber si algún SNPs se encuentran asociados a alguna variable ambiental y si este patrón se repite en los distintos sitios analizados.

## Métodos

### Trabajo de campo

El estudio fue realizado en cuatro sitios, dos perturbados (P6Agr y P5Agr) y dos naturales (P6For y P5For), ubicados en dos localidades distintas. Uno a las faldas del Volcán Iztaccíhuatl (P6) y el otro en el Monte Tlaloc (P5). Los individuos de *S. grammicus* capturados se les tomó la coordenada geográfica y una pequeña muestra de tejido de la cola, para su posterior procesamiento en el laboratorio. En cada sitio de captura se registraron variables abióticas del paisaje, tal como temperatura del aire y del suelo, humedad relativa y altura. También se registró datos de presencia o ausencia de caminos, cultivos, asentamientos y tipo de vegetación.

### Análisis del paisaje

Para analizar las diferencias de los paisajes perturbados y naturales, se prosiguió a realizar diversos análisis con las variables tomadas en campo. Los datos de presencia se usaron para realizar un análisis de clasificación supervisada de uso de suelos, usando el programa QGIS v.3.22. Esta clasificación fue usada posteriormente en el programa Fragstats v.4.2 para estimar el área de cada tipo de parche. Asimismo, con los datos de altura se prosiguió a calcular la pendiente del terreno. Usando imágenes satelitales Sentinel 2, se calculó el Índice de vegetación normalizada (NDVI) y el Índice de estrés por humedad (MSI). Todos estos análisis se realizaron usando el programa QGIS v.3.22. Finalmente, en r para cada variable se realizaron pruebas de Wilcoxon para evaluar si existían diferencias significativas entre sitios dentro de cada localidad.

### Análisis genómicos

De cada sitio de estudio se utilizaron 10 individuos, de los cuales su ADN fue extraído y secuenciado mediante ddrad-seq, usando un secuenciador Illumuna Hiseq 2000. Los datos genómicos brutos fueron filtrados y ensamblados *de novo* previamente, usando programas como Trimmomatic v,0.36, Stacks v.2.60 y VCFtool v.0.1.16. Finalmente, se obtuvo una base de datos con 7599 SNPs, con la que se realizó los análisis posteriores.

Para la detección del número de clusters más probable entre sitios, se usó la función `find clusters` y un análisis discriminante de componente principales (DAPC), empleando el paquete adegenet v.2.1.5. Después se prosiguió a estimar la diversidad genética de cada grupo con el mismo paquete y el coeficiente de diferenciación FST usando el paquete hierfstat v.0.5-11.

La detección de outliers se hizo usando dos programas diferentes, BayeScan v.2.01 y BayPass v2.3. El primero identifica loci candidatos bajo selección en datos genéticos, usando diferencias en las frecuencias alélicas entre un acervo genético común, por lo que emplea el coeficiente FST para ello. El segundo Identifica marcadores genéticos sujetos a selección asociados a covariables específicas de una población, tal como variables ambientales o características fenotípicas cuantitativas o categóricas. Los análisis se hicieron entre sitios dentro de cada localidad y las variables ábioticas obtenidas y generadas fueron correlacionadas (descartando las variables altamente correlacionadas) y estandarizadas para el análisis con BayPass.

## Resultados

### Análisis del paisaje

En cuanto al área ocupada para cada parche se observó que, dentro de las áreas naturales (P6For y 5For), el que predominó fue el bosque de coníferas, y estos no presentaron zonas agrícolas. Con especto a las zonas perturbadas (P6Agr y P5Agr), igualmente hubo predominio del bosque, pero hubo una mayor proporción de área ocupa por zonas agrícolas y de suelo desnudo, además de mayor presencia de caminos. En cuanto a las pruebas Wilcoxon, la humedad relativa, pendiente, altura y el índice de estrés por humedad, presentaron diferencias significativas entre sitios dentro de cada localidad.

### Análisis genómico

El análisis con `find clusters` y DAPC mostró que el número de clusters más probable fue de cuatro, separando a los individuos según su sitio de muestreo. En cuanto a los valores de diversidad, el sitio perturbado P5Agr fue el que mostró una mayor heterocigosidad (observada y esperada) con respecto a los otros tres sitios. Mientras que el sitio P5For mostró los menores valores. Con respecto al coeficiente FST los valores más altos de diferenciación los presentó el sitio P6For, el cual estaba claramente separado de los otros tres según el DAPC. Entre los otros tres sitios su diferenciación fue moderada.

El análisis con BayeScan para detectar SNPs outliers encontró en cada par de sitios un solo SNP candidato bajo selección, el cual fue distinto entre localidades. En cuanto al análisis con BayPass para la localidad P6 se encontraron 19 SNPs asociados a una variable ambiental, siendo la humedad relativa, la altura y la pendiente los que tuvieron una mayor asociación y con correlaciones positivas. Para el sitio P5 solo se encontraron dos, que tuvieron una mayor asociación con las variables altura y NDVI, mostrando una correlación positiva y con la pendiente, pero con una correlación negativa.

## Referencias

Audet, J.-N., Ducatez, S. & Lefebvre, L. The town bird and the country bird: problem solving and immunocompetence vary with urbanization. Behav. Ecol. 27, 637–644 (2016).

Argaez-Márquez. Selección sexual en un gradiente de urbanización en la lagartija del mezquite (*Sceloporus grammicus microlepidotus*). Tesis para obtener el grado de Maestro en Ciencias, UNAM (2015).

Campbell-Staton, S. C. et al. Parallel selection on thermal physiology facilitates repeated adaptation of city lizards to urban heat islands. Nat. Ecol. Evol. 4, 652–658 (2020).

Reid, N. M. et al. The genomic landscape of rapid repeated evolutionary adaptation to toxic pollution in wild fish. Science 354, 1305–1308 (2016).

Winchell, K. M., Reynolds, R. G., Prado‐Irwin, S. R., Puente‐Rolón, A. R. & Revell, L. J. Phenotypic shifts in urban areas in the tropical lizard Anolis cristatellus. Evolution 70, 1009–1022 (2016).

Winchell, K. M., Maayan, I., Fredette, J. R. & Revell, L. J. Linking locomotor performance to morphological shifts in urban lizards. Proc. R. Soc. B Biol. Sci. 285, 20180229 (2018).

Hendry, A. P., Farrugia, T. J. & Kinnison, M. T. Human influences on rates of phenotypic change in wild animal populations. Mol. Ecol. 17, 20–29 (2008).
